### PR TITLE
Add multisample support and various other improvements

### LINKED ISSUE #2: Improve treatment of  row.GT and row.FILTER
Hi there

I think the SNPIT code assumes two things  - i could be completely wrong btw, do please correct me if so. I think the assumptions are

1. if a record does not have . or 0 as the genotype, then it is a record with an actual non-reference call
2. the filter column can be ignored as all records are good.

I'm afraid both are false,  in terms of clockwork output.
Basically the problem is clockwork runs in diploid mode to allow het calls, and so will output stuff like 0/0

I think that if you put here ish:
https://github.com/philipwfowler/snpit/blob/b65f1abe6d7ee174e69dd1ed4b8db68321650cc7/snpit/core.py#L129

checks to ensure the FILTER is PASS, and that the genotype is not 0 or 0/0, then everything should be fine. But you can get VCF records where the genotype is REF. In  particular, Clockwork, when combining calls from multiple samples, and then regenotyping/joint-genotyping all samples at all sites, to get a set of VCFs with all the same records (in terms of chr/pos/ref/alt alleles), can definitely have REF calls that are 0/0.

As a result, SNPiT currently mis-calls lots of samples.

### PR DESCRIPTION
**Pull request by mbhall88**
Hey @philipwfowler ,

You are obviously very welcome to reject this, but I thought I would put in a PR just in case you want to incorporate the changes I have made.  

I have changed a lot, but the underlying method/logic remains the same (I hope). 

### Add multisample support
This addresses #3 . snpit will now handle both multisample VCF and FAST(A/Q) and write their output to the same output file.

### Change output format
I have changed the output format to be tab-delimited with one sample per-line. See https://github.com/mbhall88/snpit#output-format for an example.

### Speedup
By changing the VCF/FAST(A/Q) API to [`pysam`](https://pysam.readthedocs.io/en/latest/#) (plus some procedural optimisations in the code) I have been able to speedup snpit and also reduce the external dependencies from `biopython` and `pyvcf` to just `pysam`.  
As an example, a 67Mb VCF ran in ~23 seconds with the original snpit. This new version now runs in ~2 seconds.  
I also tested it out on a 51Gb VCF with 3374 samples and it took ~13 minutes and used only 146Mb RAM.

### Refactor
I also refactored the code fairly extensively. I moved some things out into their own classes, added lots of tests, and also moved the entry point for the program out of the `bin/snpit-runner.py` script into the project's `main` function.

### Packaging
I have set everything up in such a way that it should be quite easy to package this and upload to pypi so that it is `pip`-installable. Once up on `pip` I will also create a bioconda recipe.

### VCF compatibility
Part of the changes also help handling VCF fields and genotypes a bit more robustly (closes #2 ). See [here](https://github.com/mbhall88/snpit#vcf-input-and-only-use-records-that-have-pass-in-the-filter-field) and [here](https://github.com/mbhall88/snpit#filtering-vcf-based-on-status-field) for examples.

### CODE REVIEW

**Comment by mbhall88** [comment]
Also, please test this out on your end too. I have tested a few VCFs and fasta files on my end and cross checked some classifications with mykrobe. All results seem to be same and the same as the previous version. But you can never test enough I guess.

**Comment by mbhall88** [comment]
I also just noticed that Sam's fork as a newer version of the libraries. I have added those in now.

**Comment by philipwfowler** [comment]
Hey thanks @mbhall88!

It is great to receive a pull request (it is actually my first one..).  This repo is a simple reworking of SNPT, that was developed by Sam Lipworth who is a clinical researcher here in Oxford.

I'll take a look and since we use this to process both CRyPTIC and SP3 data, the performance increases would be very welcome (e.g. when I'm dealing with the 50k TB genomes Zam is about to give me.

It might take me a little while to get back to you as I'm busy and not done this before, and I can't think why I wouldn't accept all your changes but I should definitely look to check they don't break anything downstream in CRyPTIC or SP3.

**Comment by mbhall88** [comment]
No problems. There is no rush. I wouldn't want you to accept it until you were convinced it is correct anyway.  
Let me know if you run into any issues with it and I will commit any fixes to this PR.

**Comment by philipwfowler** [comment]
Have cloned your repo and having problems installing. Think it might be because I am using Python 3.5.6. If I try 
```
$ python setup.py install --user
```

I get complaints about

```
File "/Users/fowler/packages/mbhall/snpit/snpit/snpit.py", line 132
    determined: {genotype.call()}.\nPlease raise this with the developers."""
                                                                            ^
SyntaxError: invalid syntax```

Any ideas?

**Comment by mbhall88** [comment]
Yeah the codebase is only compatible with 3.6 with the way I have written it (see https://github.com/mbhall88/snpit#installation)  

I can go through and make it 3.5 compatible if you would prefer.

**Comment by philipwfowler** [comment]
Would you mind making it 3.5 compatible? Our main cluster here in Oxford has python3.5.2 as its most up to date and I don't want to go down the container route unless I absolutely have to.

**Comment by mbhall88** [comment]
Hi @philipwfowler That should be fixed now in https://github.com/philipwfowler/snpit/pull/4/commits/e363c0914aa4f4769a2b948d563b0a39d307b949

**Comment by philipwfowler** [comment]
Thanks. Bumped into a few problems, mainly brought about that your understanding of packaging is > mine. If I try 

```
$ sudo python setup.py install
```

I get

```
running install_data
creating build/bdist.macosx-10.14-x86_64/egg/data
error: can't copy 'data/img/logo.png': doesn't exist or not a regular file
```

If I try a `python setup.py install --user` install, I also get 

```
running install_data
creating /etc/my_package
error: could not create '/etc/my_package': Permission denied
```

Both of these errors seem to originate in `setup.cfg`

```
[options.data_files]
/etc/my_package =
    site.d/00_default.conf
    host.d/00_default.conf
data = data/img/logo.png, data/svg/icon.svg
```

since it is forcing python to write to `/etc/` even if doing a `--user` install and there is no `data/` folder. So if I delete *all* of the above and try again with a `--user` install it works, so if I try

```
$ snpit --input example/example.vcf 
...
FileNotFoundError: [Errno 2] No such file or directory: '/Users/fowler/Library/Python/3.5/lib/python/site-packages/snpit-1.0.0-py3.5.egg/lib/library.csv'
```

So when I look this is all I see (i.e. no `lib/`)

```
$ ls ~/Library/Python/3.5/lib/python/site-packages/snpit-1.0.0-py3.5.egg/
EGG-INFO snpit    tests
```

Hope being verbose helps, but am trying to run all the bugs down I can in one go! Thanks for all your help - I am very interested in `pysam` being faster than `PyVCF` since I use the later in another repo, `piezo` that consumes all the 50k TB VCFs Zam is making so speed is going to matter...

**Comment by mbhall88** [comment]
Ooo good catch. Sorry that `/etc` stuff should not have been in there. It was leftover from a template I think. Have updated, could you please try again?

**Comment by philipwfowler** [comment]
Installs fine now with python3.5 but I still get

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/fowler/Library/Python/3.5/lib/python/site-packages/snpit-1.0.0-py3.5.egg/lib/library.csv'
```

when I try and process the example vcf

**Comment by mbhall88** [comment]
Apologies for the errors Phil. This is actually also my first time trying out this style of package setup. So naturally, there are some teething issues. Thank you for persisting.  

Ok, let's see if the latest commit helps.

**Comment by philipwfowler** [comment]
Don't apologise - I really appreciate your help and am learning how to better package myself.

Still barfs on `lib/`.

```
creating build/bdist.macosx-10.14-x86_64/egg/lib
error: can't copy 'lib/*': doesn't exist or not a regular file
```

The line in `setup.cfg` is 

```
[options.data_files]
lib = lib/*
```

If I delete all that it installs, but then can't find `library.csv` predictably! I've tried changing the foo in and also specifying the folder via `MANIFEST.in` but am really just trying random things and seeing if they work. What puzzles me is how `tests/` is specified to be copied. Tried Googling but nothing obvious to me. 

The problem seems to be the wildcard. If I specify 

```
[options.data_files]
lib = lib/library.csv
```
Then it does work, but obv. we are missing all the lineage files. Could just list 'em all, but does feel Pythonic to me.

**Comment by mbhall88** [comment]
Ok. So I was able to recreate this (and solve) in a clean virtual machine.

So can you pull the changes and run the following from inside the project directory.

```sh
python3 setup.py install --user
```

Just for clarification where are you running these commands? Are you using a virtual environment? When you use the `--user` flag with installation you need to make sure you have `~/.local/bin` in your `PATH`. Apologies if you know all of this. Just wanting to make sure we are on the same page.

**Comment by philipwfowler** [comment]
np. Installs fine as you say via

`python3 setup.py install --user`

(which is what I was doing, and I have `$PATH` setup correctly). If I then try and run the example via

```
$ snpit -i example/example.vcf 
...
  File "/Users/fowler/tmp/snpit/snpit/snpit.py", line 63, in count_lineage_classifications_for_samples_in_vcf
    vcf = pysam.VariantFile(vcf_path)
  File "pysam/libcbcf.pyx", line 4015, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4232, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 540, in pysam.libchtslib.HTSFile._open_htsfile
AttributeError: 'PosixPath' object has no attribute 'fileno'
```
which looks like something to do with the path to the VCF, so if I instead do

```
$ cd example/
$ snpit -i example.vcf
...
    return self._accessor.open(self, flags, mode)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'lib/library.csv'
```

Revealing the second error! This is all  not using a virtualenv.  If I first follow the instructions on the README and do 

```
# this installs snpit and dependencies inside a new virtual environment
pipenv install -e . pysam pytest
# activate the virtual environment
pipenv shell
# make sure it is working
pytest
```

Then `pytest` fails 

```
(snpit) ndmpc222 507 $ pytest
============================= test session starts ==============================
platform darwin -- Python 3.5.6, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/fowler/tmp/snpit, inifile: pytest.ini, testpaths: tests/
collected 72 items                                                             

tests/test_genotype.py ...................................               [ 48%]
tests/test_lineage.py ..............                                     [ 68%]
tests/test_snpit.py FFFF..FFFFFF.......FFFF                              [100%]
```

with a lot of 

`E   AttributeError: 'PosixPath' object has no attribute 'fileno'`

Can't find much specific on Google. Wondering if this is a Python 3.6->3.5 thing?

Would this be easier via Slack? We have a CRyPTIC workspace but I'm also on µbioinfo or I could join the iqballab one.

**Comment by mbhall88** [comment]
Ah yes, this is a python 3.6 -> 3.5 thing (see [here](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep519)).  

Slack might be better. Happy to join the cryptic one (michael.hall@ebi.ac.uk)

**Comment by philipwfowler** [comment]
Ok, one more thing!

Having tested it more widely, it only worked if I was in `snpit/`. This is because the Path `lib/library.csv` then worked. I think there are 2 problems

1. need to install the contents of `lib/` into the egg. I needed to make this change to `setup.cfg`

```
[options.package_data]
* = *.md, *.rst, ../lib/*
```

2. then use `pkg_resources` to find these files on the fly. Needed to change 

`LIBRARY_DIR = Path("../lib/")`

 and also the following in `__init__`

```
library_csv= pkg_resources.resource_filename("snpit", str(LIBRARY_DIR / "library.csv"))
self.lineages, self.lineage_positions = load_lineages_from_csv(Path(library_csv))
```

and in `load_lineages_from_csv()`

```
lineage_variants_file= Path(pkg_resources.resource_filename("snpit", str(LIBRARY_DIR / lineage.name)))
```

It feels a bit hacky since `pkg_resources` seems to deal in strings but with `pathlib` we can use `Path` objects but I don't know enough about this to know if there is way of getting the two to play nicely together or simply accept that you have to convert the string into a Path object.

Then I can call `snpit` from anywhere in the filesystem and give a relative path to `--input` and it is happy.

Could you please make the changes and then I'll merge?

**Comment by mbhall88** [comment]
Ok so I think part of the problem may have been that I wasn't including the lib files in the MANIFEST. I am now a little more verbose in how I point at the `lib` directory.  

This is effectively an attempt to do what you did but in a slightly less "hackier" way. If this still doesn't work I will just use the exact method you used.

**Comment by philipwfowler** [comment]
Almost works! Had to do one change in `setup.cfg`

```
[options.package_data]
* = *.md, *.rst, ../lib/*
```

otherwise it still can't find `library.csv`

**Comment by mbhall88** [comment]
Ah, [`package_data` is treated](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files) as though it is inside the `snpit` module directory. Weird.

**Pull request merged**
